# Generated by Django 5.0.6 on 2024-05-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='region',
            field=models.CharField(blank=True, choices=[('DVFO', 'ДВФО'), ('MMO', 'Москва и МО'), ('PFO', 'ПФО'), ('SZFO', 'СЗФО'), ('SKFO', 'СКФО'), ('SFO', 'СФО'), ('UFO', 'УФО'), ('CFO', 'ЦФО'), ('YFO', 'ЮФО')], max_length=255, null=True),
        ),
    ]
