# Generated by Django 5.0.6 on 2024-06-02 18:06

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AddField(
            model_name='contact',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Директор или иной представитель'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), blank=True, null=True, size=20, verbose_name='Адреса эл.почт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='inn',
            field=models.PositiveBigIntegerField(verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='kpp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phones',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=20, verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='region',
            field=models.CharField(blank=True, choices=[('DVFO', 'ДВФО'), ('MMO', 'Москва и МО'), ('PFO', 'ПФО'), ('SZFO', 'СЗФО'), ('SKFO', 'СКФО'), ('SFO', 'СФО'), ('UFO', 'УФО'), ('CFO', 'ЦФО'), ('YFO', 'ЮФО')], max_length=255, null=True, verbose_name='Федеральный округ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
