# Generated by Django 5.0.6 on 2024-06-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_options_contact_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inn',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ИНН'),
        ),
    ]
