version: '3'

services:
  web:
    build: .
    command: bash -c "
      python manage.py migrate
      && supervisord -n"
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - redis
      - db
    networks:
      - djangonetwork

  redis:
    image: redis:6.2.14-alpine
    ports:
      - "6379:6379"
    networks:
      - djangonetwork

  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: bitrix_casebook_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - djangonetwork
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./static:/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - djangonetwork
volumes:
  static:
  pgdata:

networks:
  djangonetwork:
    driver: bridge